function TIE = jointToTIE(q)
    TIE = jointToTI0(q)*...
          jointToT01(q)*...
          jointToT12(q)*...
          jointToT23(q)*...
          jointToT34(q)*...
          %jointToT45(q)*...
          jointToT56(q)*...
          jointToT6E(q);
end

